/*

 * Initializing.c

 *
 *  Created on: Dec 13, 2016
 *      Author: Russel
 *
 *    Version : 2
 *
 */
#include "std_types.h"
#include "io_ports_atmega32.h"
#include "DIO_Interface.h"
#include "DIO_Config.h"
//#include "DIO_Private.h"
#include "utils.h"
#include "DIO_voidInitialize.h"

void DIO_voidInitialize()
{

DDRA = DDRA_VALUE( DIO_u8PIN_0_DIRECTION , DIO_u8PIN_1_DIRECTION , DIO_u8PIN_2_DIRECTION,
		DIO_u8PIN_3_DIRECTION,DIO_u8PIN_4_DIRECTION,DIO_u8PIN_5_DIRECTION,DIO_u8PIN_6_DIRECTION,DIO_u8PIN_7_DIRECTION);

DDRB = DDRB_VALUE(DIO_u8PIN_8_DIRECTION,DIO_u8PIN_9_DIRECTION, DIO_u8PIN_10_DIRECTION,

		DIO_u8PIN_11_DIRECTION , DIO_u8PIN_12_DIRECTION, DIO_u8PIN_13_DIRECTION,DIO_u8PIN_14_DIRECTION,DIO_u8PIN_15_DIRECTION);

DDRC=DDRC_VALUE(DIO_u8PIN_16_DIRECTION,DIO_u8PIN_17_DIRECTION,DIO_u8PIN_18_DIRECTION,
		DIO_u8PIN_19_DIRECTION,DIO_u8PIN_20_DIRECTION,DIO_u8PIN_21_DIRECTION,DIO_u8PIN_22_DIRECTION,DIO_u8PIN_23_DIRECTION);

DDRD=DDRD_VALUE(DIO_u8PIN_24_DIRECTION,DIO_u8PIN_25_DIRECTION,DIO_u8PIN_26_DIRECTION,
		DIO_u8PIN_27_DIRECTION,DIO_u8PIN_28_DIRECTION,DIO_u8PIN_29_DIRECTION,DIO_u8PIN_30_DIRECTION,DIO_u8PIN_31_DIRECTION);



PORTA=PORTA_VALUE(DIO_u8PIN_7_INITIAL,DIO_u8PIN_6_INITIAL,DIO_u8PIN_5_INITIAL,DIO_u8PIN_4_INITIAL,DIO_u8PIN_3_INITIAL,
		DIO_u8PIN_2_INITIAL,DIO_u8PIN_1_INITIAL,DIO_u8PIN_0_INITIAL);

PORTB=PORTB_VALUE(DIO_u8PIN_15_INITIAL,DIO_u8PIN_14_INITIAL,DIO_u8PIN_13_INITIAL,DIO_u8PIN_12_INITIAL,DIO_u8PIN_11_INITIAL,
		DIO_u8PIN_10_INITIAL,DIO_u8PIN_9_INITIAL,DIO_u8PIN_8_INITIAL);

PORTC=PORTC_VALUE(DIO_u8PIN_23_INITIAL,DIO_u8PIN_22_INITIAL,DIO_u8PIN_21_INITIAL,DIO_u8PIN_20_INITIAL,DIO_u8PIN_19_INITIAL,
		DIO_u8PIN_18_INITIAL,DIO_u8PIN_17_INITIAL,DIO_u8PIN_16_INITIAL);

PORTD=PORTD_VALUE(DIO_u8PIN_31_INITIAL,DIO_u8PIN_30_INITIAL,DIO_u8PIN_29_INITIAL,DIO_u8PIN_28_INITIAL,DIO_u8PIN_27_INITIAL,
		DIO_u8PIN_26_INITIAL,DIO_u8PIN_25_INITIAL,DIO_u8PIN_24_INITIAL);

}

