/*
 * KEYPAD.h
 *
 *  Created on: Jan 30, 2017
 *      Author: root
 */

#ifndef KEYPAD_H_
#define KEYPAD_H_

#define ERROR 0
#define OK 1
#define HIGH 1
#define LOW 0

#define KEYPAD_BITNUMBERS_MAXIMUM 4
#define KEYPAD_BITNUMBERS_INITIAL 0

#define KEYPAD_ROW1COLUMN1  1
#define KEYPAD_ROW1COLUMN2  2
#define KEYPAD_ROW1COLUMN3  3
#define KEYPAD_ROW1COLUMN4  'A'


#define KEYPAD_ROW2COLUMN1 4
#define KEYPAD_ROW2COLUMN2 5
#define KEYPAD_ROW2COLUMN3 6
#define KEYPAD_ROW2COLUMN4 'B'


#define KEYPAD_ROW3COLUMN1 7
#define KEYPAD_ROW3COLUMN2 8
#define KEYPAD_ROW3COLUMN3 9
#define KEYPAD_ROW3COLUMN4 'C'


#define KEYPAD_ROW4COLUMN1 '*'
#define KEYPAD_ROW4COLUMN2 0
#define KEYPAD_ROW4COLUMN3 'Enter'
#define KEYPAD_ROW4COLUMN4 'D'

#define KEYPAD_ROW1 PIN_16
#define KEYPAD_ROW2 PIN_17
#define KEYPAD_ROW3 PIN_18
#define KEYPAD_ROW4 PIN_19

#define KEYPAD_Coloumn1  PIN_20
#define KEYPAD_Coloumn2  PIN_21
#define KEYPAD_Coloumn3  PIN_22
#define KEYPAD_Coloumn4  PIN_23

#define KEYPAD_DEFAULT_FLAG 0


#define KEYPAD_ROW1SELECTED 1
#define KEYPAD_ROW2SELECTED 2
#define KEYPAD_ROW3SELECTED 3
#define KEYPAD_ROW4SELECTED 4

#define KEYPAD_Coloumn1SELECTED 1
#define KEYPAD_Coloumn2SELECTED 2
#define KEYPAD_Coloumn3SELECTED 3
#define KEYPAD_Coloumn4SELECTED 4

#define KEYPAD_ROW1ON 0b00001110
#define KEYPAD_ROW2ON 0b00001101
#define KEYPAD_ROW3ON 0b00001011
#define KEYPAD_ROW4ON 0b00000111

#define KEYPAD_ROWS_COUNTER_INITIAL 0
#define KEYPAD_ROWS_COUNTER_MAXIMUM 4


#define KEYPAD_COLOUMN_COUNTER_INITIAL 4
#define KEYPAD_COLOUMN_COUNTER_MAXIMUM 8

#define KEYPAD_CALCULATE_KEYPRESSED(LOCAL_u8ROW_INDEX) ( 3*LOCAL_u8ROW_INDEX+LOCAL_u8ROW_INDEX+1)

u8 KEYPAD_u8GetKeyValue(u8 Copy_u8PinNumber,pu8 Copy_pu8KeyStatus);
u8 KEYPAD_u8Init(void);

#endif /* KEYPAD_H_ */
