/*
 * pripherals.h
 *
 *  Created on: Jan 11, 2017
 *      Author: Russel
 */

#ifndef PRIPHERALS_H_
#define PRIPHERALS_H_

//KEYPAD


#define KEYPAD_FIRST_ROW 24
#define KEYPAD_SECOND_ROW 25
#define KEYPAD_THIRD_ROW 26
#define KEYPAD_FOURTH_ROW 27
#define KEYPAD_FIRST_COLOUMN 16
#define KEYPAD_SECOND_COLOUMN 17
#define KEYPAD_THIRD_COLOUMN 18
#define KEYPAD_FOURTH_COLOUMN 19
#define KEYPAD_FIRST_LED 0
#define KEYPAD_SECOND_LED 1
#define KEYPAD_THIRD_LED 2
#define KEYPAD_FOURTH_LED 3

#define MOTOR_DIRECTION_ONE_UPPER 16
#define MOTOR_DIRECTION_ONE_LOWER 17
#define MOTOR_DIRECTION_TWO_UPPER 19
#define MOTOR_DIRECTION_TWO_LOWER 18
#endif /* PRIPHERALS_H_ */
